// Code generated by MockGen. DO NOT EDIT.
// Source: ./app/domain/spotify/artist/artist_repository.go
//
// Generated by this command:
//
//	mockgen -source=./app/domain/spotify/artist/artist_repository.go -destination=./app/domain/spotify/artist/artist_repository_mock.go -package=artist
//

// Package artist is a generated GoMock package.
package artist

import (
	context "context"
	reflect "reflect"

	spotify "github.com/zmb3/spotify/v2"
	gomock "go.uber.org/mock/gomock"
)

// MockArtistRepository is a mock of ArtistRepository interface.
type MockArtistRepository struct {
	ctrl     *gomock.Controller
	recorder *MockArtistRepositoryMockRecorder
	isgomock struct{}
}

// MockArtistRepositoryMockRecorder is the mock recorder for MockArtistRepository.
type MockArtistRepositoryMockRecorder struct {
	mock *MockArtistRepository
}

// NewMockArtistRepository creates a new mock instance.
func NewMockArtistRepository(ctrl *gomock.Controller) *MockArtistRepository {
	mock := &MockArtistRepository{ctrl: ctrl}
	mock.recorder = &MockArtistRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockArtistRepository) EXPECT() *MockArtistRepositoryMockRecorder {
	return m.recorder
}

// FindById mocks base method.
func (m *MockArtistRepository) FindById(ctx context.Context, id spotify.ID) (*Artist, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindById", ctx, id)
	ret0, _ := ret[0].(*Artist)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindById indicates an expected call of FindById.
func (mr *MockArtistRepositoryMockRecorder) FindById(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindById", reflect.TypeOf((*MockArtistRepository)(nil).FindById), ctx, id)
}

// FindByNameLimit mocks base method.
func (m *MockArtistRepository) FindByNameLimit(ctx context.Context, name string, limit int) ([]*Artist, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByNameLimit", ctx, name, limit)
	ret0, _ := ret[0].([]*Artist)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByNameLimit indicates an expected call of FindByNameLimit.
func (mr *MockArtistRepositoryMockRecorder) FindByNameLimit(ctx, name, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByNameLimit", reflect.TypeOf((*MockArtistRepository)(nil).FindByNameLimit), ctx, name, limit)
}

// IsLiked mocks base method.
func (m *MockArtistRepository) IsLiked(ctx context.Context, id spotify.ID) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsLiked", ctx, id)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsLiked indicates an expected call of IsLiked.
func (mr *MockArtistRepositoryMockRecorder) IsLiked(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsLiked", reflect.TypeOf((*MockArtistRepository)(nil).IsLiked), ctx, id)
}

// Like mocks base method.
func (m *MockArtistRepository) Like(ctx context.Context, id spotify.ID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Like", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Like indicates an expected call of Like.
func (mr *MockArtistRepositoryMockRecorder) Like(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Like", reflect.TypeOf((*MockArtistRepository)(nil).Like), ctx, id)
}

// Unlike mocks base method.
func (m *MockArtistRepository) Unlike(ctx context.Context, id spotify.ID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Unlike", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Unlike indicates an expected call of Unlike.
func (mr *MockArtistRepositoryMockRecorder) Unlike(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Unlike", reflect.TypeOf((*MockArtistRepository)(nil).Unlike), ctx, id)
}
