// Code generated by MockGen. DO NOT EDIT.
// Source: ./app/infrastructure/spotify/api/client.go
//
// Generated by this command:
//
//	mockgen -source=./app/infrastructure/spotify/api/client.go -destination=./app/infrastructure/spotify/api/client_mock.go -package=api
//

// Package api is a generated GoMock package.
package api

import (
	reflect "reflect"

	proxy "github.com/yanosea/spotlike/pkg/proxy"
	gomock "go.uber.org/mock/gomock"
)

// MockClient is a mock of Client interface.
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder
	isgomock struct{}
}

// MockClientMockRecorder is the mock recorder for MockClient.
type MockClientMockRecorder struct {
	mock *MockClient
}

// NewMockClient creates a new mock instance.
func NewMockClient(ctrl *gomock.Controller) *MockClient {
	mock := &MockClient{ctrl: ctrl}
	mock.recorder = &MockClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClient) EXPECT() *MockClientMockRecorder {
	return m.recorder
}

// Auth mocks base method.
func (m *MockClient) Auth(arg0 chan<- string, arg1 string) (proxy.Client, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Auth", arg0, arg1)
	ret0, _ := ret[0].(proxy.Client)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Auth indicates an expected call of Auth.
func (mr *MockClientMockRecorder) Auth(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Auth", reflect.TypeOf((*MockClient)(nil).Auth), arg0, arg1)
}

// Close mocks base method.
func (m *MockClient) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockClientMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockClient)(nil).Close))
}

// Open mocks base method.
func (m *MockClient) Open() proxy.Client {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Open")
	ret0, _ := ret[0].(proxy.Client)
	return ret0
}

// Open indicates an expected call of Open.
func (mr *MockClientMockRecorder) Open() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Open", reflect.TypeOf((*MockClient)(nil).Open))
}

// UpdateConfig mocks base method.
func (m *MockClient) UpdateConfig(arg0 *ClientConfig) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "UpdateConfig", arg0)
}

// UpdateConfig indicates an expected call of UpdateConfig.
func (mr *MockClientMockRecorder) UpdateConfig(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateConfig", reflect.TypeOf((*MockClient)(nil).UpdateConfig), arg0)
}
