// Code generated by MockGen. DO NOT EDIT.
// Source: ./app/infrastructure/spotify/api/client_manager.go
//
// Generated by this command:
//
//	mockgen -source=./app/infrastructure/spotify/api/client_manager.go -destination=./app/infrastructure/spotify/api/client_manager_mock.go -package=api
//

// Package api is a generated GoMock package.
package api

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockClientManager is a mock of ClientManager interface.
type MockClientManager struct {
	ctrl     *gomock.Controller
	recorder *MockClientManagerMockRecorder
	isgomock struct{}
}

// MockClientManagerMockRecorder is the mock recorder for MockClientManager.
type MockClientManagerMockRecorder struct {
	mock *MockClientManager
}

// NewMockClientManager creates a new mock instance.
func NewMockClientManager(ctrl *gomock.Controller) *MockClientManager {
	mock := &MockClientManager{ctrl: ctrl}
	mock.recorder = &MockClientManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClientManager) EXPECT() *MockClientManagerMockRecorder {
	return m.recorder
}

// CloseClient mocks base method.
func (m *MockClientManager) CloseClient() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CloseClient")
	ret0, _ := ret[0].(error)
	return ret0
}

// CloseClient indicates an expected call of CloseClient.
func (mr *MockClientManagerMockRecorder) CloseClient() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CloseClient", reflect.TypeOf((*MockClientManager)(nil).CloseClient))
}

// GetClient mocks base method.
func (m *MockClientManager) GetClient() (Client, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetClient")
	ret0, _ := ret[0].(Client)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetClient indicates an expected call of GetClient.
func (mr *MockClientManagerMockRecorder) GetClient() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetClient", reflect.TypeOf((*MockClientManager)(nil).GetClient))
}

// InitializeClient mocks base method.
func (m *MockClientManager) InitializeClient(ctx context.Context, config *ClientConfig) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InitializeClient", ctx, config)
	ret0, _ := ret[0].(error)
	return ret0
}

// InitializeClient indicates an expected call of InitializeClient.
func (mr *MockClientManagerMockRecorder) InitializeClient(ctx, config any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InitializeClient", reflect.TypeOf((*MockClientManager)(nil).InitializeClient), ctx, config)
}

// IsClientInitialized mocks base method.
func (m *MockClientManager) IsClientInitialized() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsClientInitialized")
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsClientInitialized indicates an expected call of IsClientInitialized.
func (mr *MockClientManagerMockRecorder) IsClientInitialized() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsClientInitialized", reflect.TypeOf((*MockClientManager)(nil).IsClientInitialized))
}
