// Code generated by MockGen. DO NOT EDIT.
// Source: ./pkg/proxy/randstr.go
//
// Generated by this command:
//
//	mockgen -source=./pkg/proxy/randstr.go -destination=./pkg/proxy/randstr_mock.go -package=proxy
//

// Package proxy is a generated GoMock package.
package proxy

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockRandstr is a mock of Randstr interface.
type MockRandstr struct {
	ctrl     *gomock.Controller
	recorder *MockRandstrMockRecorder
	isgomock struct{}
}

// MockRandstrMockRecorder is the mock recorder for MockRandstr.
type MockRandstrMockRecorder struct {
	mock *MockRandstr
}

// NewMockRandstr creates a new mock instance.
func NewMockRandstr(ctrl *gomock.Controller) *MockRandstr {
	mock := &MockRandstr{ctrl: ctrl}
	mock.recorder = &MockRandstrMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRandstr) EXPECT() *MockRandstrMockRecorder {
	return m.recorder
}

// Hex mocks base method.
func (m *MockRandstr) Hex(length int) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Hex", length)
	ret0, _ := ret[0].(string)
	return ret0
}

// Hex indicates an expected call of Hex.
func (mr *MockRandstrMockRecorder) Hex(length any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Hex", reflect.TypeOf((*MockRandstr)(nil).Hex), length)
}
