// Code generated by MockGen. DO NOT EDIT.
// Source: ./pkg/proxy/spotify.go
//
// Generated by this command:
//
//	mockgen -source=./pkg/proxy/spotify.go -destination=./pkg/proxy/spotify_mock.go -package=proxy
//

// Package proxy is a generated GoMock package.
package proxy

import (
	context "context"
	http "net/http"
	reflect "reflect"

	spotify "github.com/zmb3/spotify/v2"
	spotifyauth "github.com/zmb3/spotify/v2/auth"
	gomock "go.uber.org/mock/gomock"
	oauth2 "golang.org/x/oauth2"
)

// MockSpotify is a mock of Spotify interface.
type MockSpotify struct {
	ctrl     *gomock.Controller
	recorder *MockSpotifyMockRecorder
	isgomock struct{}
}

// MockSpotifyMockRecorder is the mock recorder for MockSpotify.
type MockSpotifyMockRecorder struct {
	mock *MockSpotify
}

// NewMockSpotify creates a new mock instance.
func NewMockSpotify(ctrl *gomock.Controller) *MockSpotify {
	mock := &MockSpotify{ctrl: ctrl}
	mock.recorder = &MockSpotifyMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSpotify) EXPECT() *MockSpotifyMockRecorder {
	return m.recorder
}

// NewAuthenticator mocks base method.
func (m *MockSpotify) NewAuthenticator(opts ...spotifyauth.AuthenticatorOption) Authenticator {
	m.ctrl.T.Helper()
	varargs := []any{}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "NewAuthenticator", varargs...)
	ret0, _ := ret[0].(Authenticator)
	return ret0
}

// NewAuthenticator indicates an expected call of NewAuthenticator.
func (mr *MockSpotifyMockRecorder) NewAuthenticator(opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewAuthenticator", reflect.TypeOf((*MockSpotify)(nil).NewAuthenticator), opts...)
}

// NewClient mocks base method.
func (m *MockSpotify) NewClient(client *http.Client, opts ...spotify.ClientOption) Client {
	m.ctrl.T.Helper()
	varargs := []any{client}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "NewClient", varargs...)
	ret0, _ := ret[0].(Client)
	return ret0
}

// NewClient indicates an expected call of NewClient.
func (mr *MockSpotifyMockRecorder) NewClient(client any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{client}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewClient", reflect.TypeOf((*MockSpotify)(nil).NewClient), varargs...)
}

// MockAuthenticator is a mock of Authenticator interface.
type MockAuthenticator struct {
	ctrl     *gomock.Controller
	recorder *MockAuthenticatorMockRecorder
	isgomock struct{}
}

// MockAuthenticatorMockRecorder is the mock recorder for MockAuthenticator.
type MockAuthenticatorMockRecorder struct {
	mock *MockAuthenticator
}

// NewMockAuthenticator creates a new mock instance.
func NewMockAuthenticator(ctrl *gomock.Controller) *MockAuthenticator {
	mock := &MockAuthenticator{ctrl: ctrl}
	mock.recorder = &MockAuthenticatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthenticator) EXPECT() *MockAuthenticatorMockRecorder {
	return m.recorder
}

// AuthURL mocks base method.
func (m *MockAuthenticator) AuthURL(state string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AuthURL", state)
	ret0, _ := ret[0].(string)
	return ret0
}

// AuthURL indicates an expected call of AuthURL.
func (mr *MockAuthenticatorMockRecorder) AuthURL(state any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AuthURL", reflect.TypeOf((*MockAuthenticator)(nil).AuthURL), state)
}

// Client mocks base method.
func (m *MockAuthenticator) Client(ctx context.Context, tok *oauth2.Token) *http.Client {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Client", ctx, tok)
	ret0, _ := ret[0].(*http.Client)
	return ret0
}

// Client indicates an expected call of Client.
func (mr *MockAuthenticatorMockRecorder) Client(ctx, tok any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Client", reflect.TypeOf((*MockAuthenticator)(nil).Client), ctx, tok)
}

// Token mocks base method.
func (m *MockAuthenticator) Token(ctx context.Context, state string, r *http.Request) (*oauth2.Token, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Token", ctx, state, r)
	ret0, _ := ret[0].(*oauth2.Token)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Token indicates an expected call of Token.
func (mr *MockAuthenticatorMockRecorder) Token(ctx, state, r any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Token", reflect.TypeOf((*MockAuthenticator)(nil).Token), ctx, state, r)
}

// MockClient is a mock of Client interface.
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder
	isgomock struct{}
}

// MockClientMockRecorder is the mock recorder for MockClient.
type MockClientMockRecorder struct {
	mock *MockClient
}

// NewMockClient creates a new mock instance.
func NewMockClient(ctrl *gomock.Controller) *MockClient {
	mock := &MockClient{ctrl: ctrl}
	mock.recorder = &MockClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClient) EXPECT() *MockClientMockRecorder {
	return m.recorder
}

// AddAlbumsToLibrary mocks base method.
func (m *MockClient) AddAlbumsToLibrary(ctx context.Context, ids ...spotify.ID) error {
	m.ctrl.T.Helper()
	varargs := []any{ctx}
	for _, a := range ids {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "AddAlbumsToLibrary", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddAlbumsToLibrary indicates an expected call of AddAlbumsToLibrary.
func (mr *MockClientMockRecorder) AddAlbumsToLibrary(ctx any, ids ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx}, ids...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddAlbumsToLibrary", reflect.TypeOf((*MockClient)(nil).AddAlbumsToLibrary), varargs...)
}

// AddTracksToLibrary mocks base method.
func (m *MockClient) AddTracksToLibrary(ctx context.Context, ids ...spotify.ID) error {
	m.ctrl.T.Helper()
	varargs := []any{ctx}
	for _, a := range ids {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "AddTracksToLibrary", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddTracksToLibrary indicates an expected call of AddTracksToLibrary.
func (mr *MockClientMockRecorder) AddTracksToLibrary(ctx any, ids ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx}, ids...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddTracksToLibrary", reflect.TypeOf((*MockClient)(nil).AddTracksToLibrary), varargs...)
}

// CurrentUserFollows mocks base method.
func (m *MockClient) CurrentUserFollows(ctx context.Context, t string, ids ...spotify.ID) ([]bool, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, t}
	for _, a := range ids {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CurrentUserFollows", varargs...)
	ret0, _ := ret[0].([]bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CurrentUserFollows indicates an expected call of CurrentUserFollows.
func (mr *MockClientMockRecorder) CurrentUserFollows(ctx, t any, ids ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, t}, ids...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CurrentUserFollows", reflect.TypeOf((*MockClient)(nil).CurrentUserFollows), varargs...)
}

// FollowArtist mocks base method.
func (m *MockClient) FollowArtist(ctx context.Context, id spotify.ID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FollowArtist", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// FollowArtist indicates an expected call of FollowArtist.
func (mr *MockClientMockRecorder) FollowArtist(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FollowArtist", reflect.TypeOf((*MockClient)(nil).FollowArtist), ctx, id)
}

// GetAlbum mocks base method.
func (m *MockClient) GetAlbum(ctx context.Context, id spotify.ID, opts ...spotify.RequestOption) (*spotify.FullAlbum, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, id}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetAlbum", varargs...)
	ret0, _ := ret[0].(*spotify.FullAlbum)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAlbum indicates an expected call of GetAlbum.
func (mr *MockClientMockRecorder) GetAlbum(ctx, id any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, id}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAlbum", reflect.TypeOf((*MockClient)(nil).GetAlbum), varargs...)
}

// GetAlbumTracks mocks base method.
func (m *MockClient) GetAlbumTracks(ctx context.Context, id spotify.ID, opts ...spotify.RequestOption) (*spotify.SimpleTrackPage, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, id}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetAlbumTracks", varargs...)
	ret0, _ := ret[0].(*spotify.SimpleTrackPage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAlbumTracks indicates an expected call of GetAlbumTracks.
func (mr *MockClientMockRecorder) GetAlbumTracks(ctx, id any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, id}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAlbumTracks", reflect.TypeOf((*MockClient)(nil).GetAlbumTracks), varargs...)
}

// GetArtist mocks base method.
func (m *MockClient) GetArtist(ctx context.Context, id spotify.ID) (*spotify.FullArtist, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetArtist", ctx, id)
	ret0, _ := ret[0].(*spotify.FullArtist)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetArtist indicates an expected call of GetArtist.
func (mr *MockClientMockRecorder) GetArtist(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetArtist", reflect.TypeOf((*MockClient)(nil).GetArtist), ctx, id)
}

// GetArtistAlbums mocks base method.
func (m *MockClient) GetArtistAlbums(ctx context.Context, artistId spotify.ID, ts []spotify.AlbumType, opts ...spotify.RequestOption) (*spotify.SimpleAlbumPage, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, artistId, ts}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetArtistAlbums", varargs...)
	ret0, _ := ret[0].(*spotify.SimpleAlbumPage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetArtistAlbums indicates an expected call of GetArtistAlbums.
func (mr *MockClientMockRecorder) GetArtistAlbums(ctx, artistId, ts any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, artistId, ts}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetArtistAlbums", reflect.TypeOf((*MockClient)(nil).GetArtistAlbums), varargs...)
}

// GetTrack mocks base method.
func (m *MockClient) GetTrack(ctx context.Context, id spotify.ID, opts ...spotify.RequestOption) (*spotify.FullTrack, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, id}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetTrack", varargs...)
	ret0, _ := ret[0].(*spotify.FullTrack)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTrack indicates an expected call of GetTrack.
func (mr *MockClientMockRecorder) GetTrack(ctx, id any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, id}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTrack", reflect.TypeOf((*MockClient)(nil).GetTrack), varargs...)
}

// RemoveAlbumsFromLibrary mocks base method.
func (m *MockClient) RemoveAlbumsFromLibrary(ctx context.Context, ids ...spotify.ID) error {
	m.ctrl.T.Helper()
	varargs := []any{ctx}
	for _, a := range ids {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "RemoveAlbumsFromLibrary", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveAlbumsFromLibrary indicates an expected call of RemoveAlbumsFromLibrary.
func (mr *MockClientMockRecorder) RemoveAlbumsFromLibrary(ctx any, ids ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx}, ids...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveAlbumsFromLibrary", reflect.TypeOf((*MockClient)(nil).RemoveAlbumsFromLibrary), varargs...)
}

// RemoveTracksFromLibrary mocks base method.
func (m *MockClient) RemoveTracksFromLibrary(ctx context.Context, ids ...spotify.ID) error {
	m.ctrl.T.Helper()
	varargs := []any{ctx}
	for _, a := range ids {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "RemoveTracksFromLibrary", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveTracksFromLibrary indicates an expected call of RemoveTracksFromLibrary.
func (mr *MockClientMockRecorder) RemoveTracksFromLibrary(ctx any, ids ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx}, ids...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveTracksFromLibrary", reflect.TypeOf((*MockClient)(nil).RemoveTracksFromLibrary), varargs...)
}

// Search mocks base method.
func (m *MockClient) Search(ctx context.Context, query string, t spotify.SearchType, opts ...spotify.RequestOption) (*spotify.SearchResult, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, query, t}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Search", varargs...)
	ret0, _ := ret[0].(*spotify.SearchResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Search indicates an expected call of Search.
func (mr *MockClientMockRecorder) Search(ctx, query, t any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, query, t}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Search", reflect.TypeOf((*MockClient)(nil).Search), varargs...)
}

// UnfollowArtist mocks base method.
func (m *MockClient) UnfollowArtist(ctx context.Context, id spotify.ID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnfollowArtist", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// UnfollowArtist indicates an expected call of UnfollowArtist.
func (mr *MockClientMockRecorder) UnfollowArtist(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnfollowArtist", reflect.TypeOf((*MockClient)(nil).UnfollowArtist), ctx, id)
}

// UserHasAlbums mocks base method.
func (m *MockClient) UserHasAlbums(ctx context.Context, ids ...spotify.ID) ([]bool, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx}
	for _, a := range ids {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "UserHasAlbums", varargs...)
	ret0, _ := ret[0].([]bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UserHasAlbums indicates an expected call of UserHasAlbums.
func (mr *MockClientMockRecorder) UserHasAlbums(ctx any, ids ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx}, ids...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UserHasAlbums", reflect.TypeOf((*MockClient)(nil).UserHasAlbums), varargs...)
}

// UserHasTracks mocks base method.
func (m *MockClient) UserHasTracks(ctx context.Context, ids ...spotify.ID) ([]bool, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx}
	for _, a := range ids {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "UserHasTracks", varargs...)
	ret0, _ := ret[0].([]bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UserHasTracks indicates an expected call of UserHasTracks.
func (mr *MockClientMockRecorder) UserHasTracks(ctx any, ids ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx}, ids...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UserHasTracks", reflect.TypeOf((*MockClient)(nil).UserHasTracks), varargs...)
}
