// Code generated by MockGen. DO NOT EDIT.
// Source: ./pkg/proxy/url.go
//
// Generated by this command:
//
//	mockgen -source=./pkg/proxy/url.go -destination=./pkg/proxy/url_mock.go -package=proxy
//

// Package proxy is a generated GoMock package.
package proxy

import (
	url "net/url"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockUrl is a mock of Url interface.
type MockUrl struct {
	ctrl     *gomock.Controller
	recorder *MockUrlMockRecorder
	isgomock struct{}
}

// MockUrlMockRecorder is the mock recorder for MockUrl.
type MockUrlMockRecorder struct {
	mock *MockUrl
}

// NewMockUrl creates a new mock instance.
func NewMockUrl(ctrl *gomock.Controller) *MockUrl {
	mock := &MockUrl{ctrl: ctrl}
	mock.recorder = &MockUrlMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUrl) EXPECT() *MockUrlMockRecorder {
	return m.recorder
}

// Parse mocks base method.
func (m *MockUrl) Parse(rawurl string) (*url.URL, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Parse", rawurl)
	ret0, _ := ret[0].(*url.URL)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Parse indicates an expected call of Parse.
func (mr *MockUrlMockRecorder) Parse(rawurl any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Parse", reflect.TypeOf((*MockUrl)(nil).Parse), rawurl)
}
