// Code generated by MockGen. DO NOT EDIT.
// Source: ./app/presentation/cli/spotlike/command/command.go
//
// Generated by this command:
//
//	mockgen -source=./app/presentation/cli/spotlike/command/command.go -destination=./app/presentation/cli/spotlike/command/command_mock.go -package=command
//

// Package command is a generated GoMock package.
package command

import (
	reflect "reflect"

	proxy "github.com/yanosea/spotlike/pkg/proxy"
	utility "github.com/yanosea/spotlike/pkg/utility"
	gomock "go.uber.org/mock/gomock"
)

// MockCli is a mock of Cli interface.
type MockCli struct {
	ctrl     *gomock.Controller
	recorder *MockCliMockRecorder
	isgomock struct{}
}

// MockCliMockRecorder is the mock recorder for MockCli.
type MockCliMockRecorder struct {
	mock *MockCli
}

// NewMockCli creates a new mock instance.
func NewMockCli(ctrl *gomock.Controller) *MockCli {
	mock := &MockCli{ctrl: ctrl}
	mock.recorder = &MockCliMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCli) EXPECT() *MockCliMockRecorder {
	return m.recorder
}

// Init mocks base method.
func (m *MockCli) Init(envconfig proxy.Envconfig, spotify proxy.Spotify, http proxy.Http, randstr proxy.Randstr, url proxy.Url, version string, versionUtil utility.VersionUtil) int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Init", envconfig, spotify, http, randstr, url, version, versionUtil)
	ret0, _ := ret[0].(int)
	return ret0
}

// Init indicates an expected call of Init.
func (mr *MockCliMockRecorder) Init(envconfig, spotify, http, randstr, url, version, versionUtil any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Init", reflect.TypeOf((*MockCli)(nil).Init), envconfig, spotify, http, randstr, url, version, versionUtil)
}

// Run mocks base method.
func (m *MockCli) Run() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Run")
	ret0, _ := ret[0].(int)
	return ret0
}

// Run indicates an expected call of Run.
func (mr *MockCliMockRecorder) Run() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Run", reflect.TypeOf((*MockCli)(nil).Run))
}
