// Code generated by MockGen. DO NOT EDIT.
// Source: ./app/domain/spotify/track/track_repository.go
//
// Generated by this command:
//
//	mockgen -source=./app/domain/spotify/track/track_repository.go -destination=./app/domain/spotify/track/track_repository_mock.go -package=track
//

// Package track is a generated GoMock package.
package track

import (
	context "context"
	reflect "reflect"

	spotify "github.com/zmb3/spotify/v2"
	gomock "go.uber.org/mock/gomock"
)

// MockTrackRepository is a mock of TrackRepository interface.
type MockTrackRepository struct {
	ctrl     *gomock.Controller
	recorder *MockTrackRepositoryMockRecorder
	isgomock struct{}
}

// MockTrackRepositoryMockRecorder is the mock recorder for MockTrackRepository.
type MockTrackRepositoryMockRecorder struct {
	mock *MockTrackRepository
}

// NewMockTrackRepository creates a new mock instance.
func NewMockTrackRepository(ctrl *gomock.Controller) *MockTrackRepository {
	mock := &MockTrackRepository{ctrl: ctrl}
	mock.recorder = &MockTrackRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTrackRepository) EXPECT() *MockTrackRepositoryMockRecorder {
	return m.recorder
}

// FindByAlbumId mocks base method.
func (m *MockTrackRepository) FindByAlbumId(ctx context.Context, id spotify.ID) ([]*Track, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByAlbumId", ctx, id)
	ret0, _ := ret[0].([]*Track)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByAlbumId indicates an expected call of FindByAlbumId.
func (mr *MockTrackRepositoryMockRecorder) FindByAlbumId(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByAlbumId", reflect.TypeOf((*MockTrackRepository)(nil).FindByAlbumId), ctx, id)
}

// FindByArtistId mocks base method.
func (m *MockTrackRepository) FindByArtistId(ctx context.Context, id spotify.ID) ([]*Track, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByArtistId", ctx, id)
	ret0, _ := ret[0].([]*Track)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByArtistId indicates an expected call of FindByArtistId.
func (mr *MockTrackRepositoryMockRecorder) FindByArtistId(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByArtistId", reflect.TypeOf((*MockTrackRepository)(nil).FindByArtistId), ctx, id)
}

// FindById mocks base method.
func (m *MockTrackRepository) FindById(ctx context.Context, id spotify.ID) (*Track, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindById", ctx, id)
	ret0, _ := ret[0].(*Track)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindById indicates an expected call of FindById.
func (mr *MockTrackRepositoryMockRecorder) FindById(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindById", reflect.TypeOf((*MockTrackRepository)(nil).FindById), ctx, id)
}

// FindByNameLimit mocks base method.
func (m *MockTrackRepository) FindByNameLimit(ctx context.Context, name string, limit int) ([]*Track, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByNameLimit", ctx, name, limit)
	ret0, _ := ret[0].([]*Track)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByNameLimit indicates an expected call of FindByNameLimit.
func (mr *MockTrackRepositoryMockRecorder) FindByNameLimit(ctx, name, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByNameLimit", reflect.TypeOf((*MockTrackRepository)(nil).FindByNameLimit), ctx, name, limit)
}

// IsLiked mocks base method.
func (m *MockTrackRepository) IsLiked(ctx context.Context, id spotify.ID) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsLiked", ctx, id)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsLiked indicates an expected call of IsLiked.
func (mr *MockTrackRepositoryMockRecorder) IsLiked(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsLiked", reflect.TypeOf((*MockTrackRepository)(nil).IsLiked), ctx, id)
}

// Like mocks base method.
func (m *MockTrackRepository) Like(ctx context.Context, id spotify.ID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Like", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Like indicates an expected call of Like.
func (mr *MockTrackRepositoryMockRecorder) Like(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Like", reflect.TypeOf((*MockTrackRepository)(nil).Like), ctx, id)
}

// Unlike mocks base method.
func (m *MockTrackRepository) Unlike(ctx context.Context, id spotify.ID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Unlike", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Unlike indicates an expected call of Unlike.
func (mr *MockTrackRepositoryMockRecorder) Unlike(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Unlike", reflect.TypeOf((*MockTrackRepository)(nil).Unlike), ctx, id)
}
