// Code generated by MockGen. DO NOT EDIT.
// Source: ./app/domain/spotify/album/album_repository.go
//
// Generated by this command:
//
//	mockgen -source=./app/domain/spotify/album/album_repository.go -destination=./app/domain/spotify/album/album_repository_mock.go -package=album
//

// Package album is a generated GoMock package.
package album

import (
	context "context"
	reflect "reflect"

	spotify "github.com/zmb3/spotify/v2"
	gomock "go.uber.org/mock/gomock"
)

// MockAlbumRepository is a mock of AlbumRepository interface.
type MockAlbumRepository struct {
	ctrl     *gomock.Controller
	recorder *MockAlbumRepositoryMockRecorder
	isgomock struct{}
}

// MockAlbumRepositoryMockRecorder is the mock recorder for MockAlbumRepository.
type MockAlbumRepositoryMockRecorder struct {
	mock *MockAlbumRepository
}

// NewMockAlbumRepository creates a new mock instance.
func NewMockAlbumRepository(ctrl *gomock.Controller) *MockAlbumRepository {
	mock := &MockAlbumRepository{ctrl: ctrl}
	mock.recorder = &MockAlbumRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAlbumRepository) EXPECT() *MockAlbumRepositoryMockRecorder {
	return m.recorder
}

// FindByArtistId mocks base method.
func (m *MockAlbumRepository) FindByArtistId(ctx context.Context, id spotify.ID) ([]*Album, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByArtistId", ctx, id)
	ret0, _ := ret[0].([]*Album)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByArtistId indicates an expected call of FindByArtistId.
func (mr *MockAlbumRepositoryMockRecorder) FindByArtistId(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByArtistId", reflect.TypeOf((*MockAlbumRepository)(nil).FindByArtistId), ctx, id)
}

// FindById mocks base method.
func (m *MockAlbumRepository) FindById(ctx context.Context, id spotify.ID) (*Album, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindById", ctx, id)
	ret0, _ := ret[0].(*Album)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindById indicates an expected call of FindById.
func (mr *MockAlbumRepositoryMockRecorder) FindById(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindById", reflect.TypeOf((*MockAlbumRepository)(nil).FindById), ctx, id)
}

// FindByNameLimit mocks base method.
func (m *MockAlbumRepository) FindByNameLimit(ctx context.Context, name string, limit int) ([]*Album, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByNameLimit", ctx, name, limit)
	ret0, _ := ret[0].([]*Album)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByNameLimit indicates an expected call of FindByNameLimit.
func (mr *MockAlbumRepositoryMockRecorder) FindByNameLimit(ctx, name, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByNameLimit", reflect.TypeOf((*MockAlbumRepository)(nil).FindByNameLimit), ctx, name, limit)
}

// IsLiked mocks base method.
func (m *MockAlbumRepository) IsLiked(ctx context.Context, id spotify.ID) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsLiked", ctx, id)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsLiked indicates an expected call of IsLiked.
func (mr *MockAlbumRepositoryMockRecorder) IsLiked(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsLiked", reflect.TypeOf((*MockAlbumRepository)(nil).IsLiked), ctx, id)
}

// Like mocks base method.
func (m *MockAlbumRepository) Like(ctx context.Context, id spotify.ID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Like", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Like indicates an expected call of Like.
func (mr *MockAlbumRepositoryMockRecorder) Like(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Like", reflect.TypeOf((*MockAlbumRepository)(nil).Like), ctx, id)
}

// Unlike mocks base method.
func (m *MockAlbumRepository) Unlike(ctx context.Context, id spotify.ID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Unlike", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Unlike indicates an expected call of Unlike.
func (mr *MockAlbumRepositoryMockRecorder) Unlike(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Unlike", reflect.TypeOf((*MockAlbumRepository)(nil).Unlike), ctx, id)
}
